name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./authormanage/pom.xml
          mvn clean package -f ./writemanage/pom.xml
          mvn clean package -f ./ai/pom.xml
          mvn clean package -f ./point/pom.xml
          mvn clean package -f ./libraryplatform/pom.xml
          mvn clean package -f ./subscribemanage/pom.xml
          mvn clean package -f ./outside/pom.xml

      - name: Docker Build and push for Authormanage
        uses: docker/build-push-action@v4
        with:
          context: ./authormanage
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/authormanage:latest
            ghcr.io/${{ github.repository }}/authormanage:${{ github.ref_name }}
            
      - name: Docker Build and push for Writemanage
        uses: docker/build-push-action@v4
        with:
          context: ./writemanage
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/writemanage:latest
            ghcr.io/${{ github.repository }}/writemanage:${{ github.ref_name }}
            
      - name: Docker Build and push for Ai
        uses: docker/build-push-action@v4
        with:
          context: ./ai
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ai:latest
            ghcr.io/${{ github.repository }}/ai:${{ github.ref_name }}
            
      - name: Docker Build and push for Point
        uses: docker/build-push-action@v4
        with:
          context: ./point
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/point:latest
            ghcr.io/${{ github.repository }}/point:${{ github.ref_name }}
            
      - name: Docker Build and push for Libraryplatform
        uses: docker/build-push-action@v4
        with:
          context: ./libraryplatform
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/libraryplatform:latest
            ghcr.io/${{ github.repository }}/libraryplatform:${{ github.ref_name }}
            
      - name: Docker Build and push for Subscribemanage
        uses: docker/build-push-action@v4
        with:
          context: ./subscribemanage
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/subscribemanage:latest
            ghcr.io/${{ github.repository }}/subscribemanage:${{ github.ref_name }}
            
      - name: Docker Build and push for Outside
        uses: docker/build-push-action@v4
        with:
          context: ./outside
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/outside:latest
            ghcr.io/${{ github.repository }}/outside:${{ github.ref_name }}
            
