apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscribemanage
  labels:
    app: subscribemanage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscribemanage
  template:
    metadata:
      labels:
        app: subscribemanage
    spec:
      containers:
        - name: subscribemanage
          image: "username/subscribemanage:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
