---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authormanage
  labels:
    app: authormanage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authormanage
  template:
    metadata:
      labels:
        app: authormanage
    spec:
      containers:
        - name: authormanage
          image: username/authormanage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: writemanage
  labels:
    app: writemanage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writemanage
  template:
    metadata:
      labels:
        app: writemanage
    spec:
      containers:
        - name: writemanage
          image: username/writemanage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai
  labels:
    app: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
        - name: ai
          image: username/ai:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: point
  labels:
    app: point
spec:
  replicas: 1
  selector:
    matchLabels:
      app: point
  template:
    metadata:
      labels:
        app: point
    spec:
      containers:
        - name: point
          image: username/point:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: libraryplatform
  labels:
    app: libraryplatform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libraryplatform
  template:
    metadata:
      labels:
        app: libraryplatform
    spec:
      containers:
        - name: libraryplatform
          image: username/libraryplatform:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscribemanage
  labels:
    app: subscribemanage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscribemanage
  template:
    metadata:
      labels:
        app: subscribemanage
    spec:
      containers:
        - name: subscribemanage
          image: username/subscribemanage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: outside
  labels:
    app: outside
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outside
  template:
    metadata:
      labels:
        app: outside
    spec:
      containers:
        - name: outside
          image: username/outside:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: authormanage
  labels:
    app: authormanage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: authormanage


---


apiVersion: v1
kind: Service
metadata:
  name: writemanage
  labels:
    app: writemanage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: writemanage


---


apiVersion: v1
kind: Service
metadata:
  name: ai
  labels:
    app: ai
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ai


---


apiVersion: v1
kind: Service
metadata:
  name: point
  labels:
    app: point
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: point


---


apiVersion: v1
kind: Service
metadata:
  name: libraryplatform
  labels:
    app: libraryplatform
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: libraryplatform


---


apiVersion: v1
kind: Service
metadata:
  name: subscribemanage
  labels:
    app: subscribemanage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: subscribemanage


---


apiVersion: v1
kind: Service
metadata:
  name: outside
  labels:
    app: outside
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: outside

