apiVersion: apps/v1
kind: Deployment
metadata:
  name: authormanage
  labels:
    app: authormanage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authormanage
  template:
    metadata:
      labels:
        app: authormanage
    spec:
      containers:
        - name: authormanage
          image: "username/authormanage:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
